### ISSUE TITLE
Please add image to readme to make this look sexy

### ISSUE THREAD

**Issue by mohammedabdulwahhab** [tajshaik24/textdigest#1]

**Comment by mohammedabdulwahhab** [comment]
Hello I need resolution on this @tajshaik24

**Comment by mohammedabdulwahhab** [comment]
This is ridiculous, I am blocked on this issue @tajshaik24 . How many story points do you expect this issue to be

**Comment by tajshaik24** [comment]
we are getting this resolved very shortly, sorry for the immense delay.
